services:
  postgres:
    image: postgres:16.0-alpine3.18
    container_name: postgres-sql-ace-player
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aceplayerdb
      POSTGRES_LOCAL_PORT: 5433
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-aceplayer
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  aceplayer-api:
    container_name: aceplayer-api
    image: aceplayer/aceplayer:1.0.1
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres
  aceplayer-ui:
    container_name: aceplayer-ui
    image: aceplayer/aceplayer-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - aceplayer-api

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local