spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/aceplayer_db"
    username: aceplayer_postgres_user
    password: 123456
    driver-class-name: org.postgresql.Driver

api:
  security:
    token:
      secret: '${JWT_SECRET:my-secret-key}'